### ISSUE TITLE
Validation error foud in dbb.load_rdb_data('diginetica') 

### ISSUE THREAD

**Issue by TristonC** [awslabs/multi-table-benchmark#1]
Got error while load the 'diginetica' dataset and it gave validation error.  Later tried other dataset, several of them show different validation errors. 
 - Tied bother version of pydantic 2.7.0 and 2.7.1. 
 -  Python version 3.10.12
```python
import dbinfer_bench as dbb 
dataset = dbb.load_rdb_data('diginetica')
```
The dataset works:
- avs
- stackexchange

The datasets do not work:
- mag
- diginetica
- retailrocket
- seznam
- amazon
- outbrain

```bash
In [3]: dataset = dbb.load_rdb_data('diginetica')
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[3], line 1
----> 1 dataset = dbb.load_rdb_data('diginetica')

File /usr/local/lib/python3.10/dist-packages/dbinfer_bench/rdb_dataset.py:177, in load_rdb_data(name_or_path)
    175 def load_rdb_data(name_or_path : str) -> DBBRDBDataset:
    176     path = download_or_get_path(name_or_path)
--> 177     return DBBRDBDataset(path)

File /usr/local/lib/python3.10/dist-packages/dbinfer_bench/rdb_dataset.py:54, in DBBRDBDataset.__init__(self, path)
     49 def __init__(
     50     self,
     51     path : Path
     52 ):
     53     self.path = Path(path)
---> 54     self._metadata = self._load_metadata()
     55     self._load_data()

File /usr/local/lib/python3.10/dist-packages/dbinfer_bench/rdb_dataset.py:58, in DBBRDBDataset._load_metadata(self)
     57 def _load_metadata(self):
---> 58     return yaml_utils.load_pyd(DBBRDBDatasetMeta, self.path / 'metadata.yaml')

File /usr/local/lib/python3.10/dist-packages/dbinfer_bench/yaml_utils.py:14, in load_pyd(pyd_model_class, path)
     12 def load_pyd(pyd_model_class, path : Path) -> pydantic.BaseModel:
     13     with open(path, "r") as f:
---> 14         return pyd_model_class.parse_obj(yaml.safe_load(f))

File /usr/local/lib/python3.10/dist-packages/pydantic/main.py:1099, in BaseModel.parse_obj(cls, obj)
   1093 @classmethod
   1094 @typing_extensions.deprecated('The `parse_obj` method is deprecated; use `model_validate` instead.', category=None)
   1095 def parse_obj(cls: type[Model], obj: Any) -> Model:  # noqa: D102
   1096     warnings.warn(
   1097         'The `parse_obj` method is deprecated; use `model_validate` instead.', category=PydanticDeprecatedSince20
   1098     )
-> 1099     return cls.model_validate(obj)

File /usr/local/lib/python3.10/dist-packages/pydantic/main.py:532, in BaseModel.model_validate(cls, obj, strict, from_attributes, context)
    530 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    531 __tracebackhide__ = True
--> 532 return cls.__pydantic_validator__.validate_python(
    533     obj, strict=strict, from_attributes=from_attributes, context=context
    534 )

ValidationError: 3 validation errors for DBBRDBDatasetMeta
tables.0.time_column
  Field required [type=missing, input_value={'name': 'Product', 'sour...g2', 'dtype': 'float'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
tables.6.time_column
  Field required [type=missing, input_value={'name': 'ProductNameToke...'link_to': 'Token.id'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
tables.7.time_column
  Field required [type=missing, input_value={'name': 'QuerySearchstri...'link_to': 'Token.id'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```

**Comment by BarclayII** [comment]
Could you try pydantic 1.10.12?

Actually, we recommend using our own [conda environment](https://github.com/awslabs/multi-table-benchmark?tab=readme-ov-file#running-baselines):
```
bash conda/install-ubuntu-deps.sh
bash conda/create_conda_env.sh
```

**Comment by BarclayII** [comment]
Fixed in https://github.com/awslabs/multi-table-benchmark/commit/f2d65645befa85f2efd39f4a46cc5176e4989825.  Could you please try again?  I verified with Pydantic 2.7.1.

**Comment by TristonC** [comment]
Thanks @BarclayII  for the fix. All work except the outbrain dataset. But it is a missing file issue now.

```bash
root@ee4304d1b0ff:/workspace/multi-table-benchmark# python test_dbb.py 
Traceback (most recent call last):
  File "/workspace/multi-table-benchmark/test_dbb.py", line 5, in <module>
    dataset = dbb.load_rdb_data(name)
  File "/workspace/multi-table-benchmark/dbinfer_bench/rdb_dataset.py", line 191, in load_rdb_data
    return DBBRDBDataset(path)
  File "/workspace/multi-table-benchmark/dbinfer_bench/rdb_dataset.py", line 68, in __init__
    self._metadata = self._load_metadata()
  File "/workspace/multi-table-benchmark/dbinfer_bench/rdb_dataset.py", line 72, in _load_metadata
    return yaml_utils.load_pyd(DBBRDBDatasetMeta, self.path / 'metadata.yaml')
  File "/workspace/multi-table-benchmark/dbinfer_bench/yaml_utils.py", line 27, in load_pyd
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outbrain/metadata.yaml'
```

**Comment by BarclayII** [comment]
Sorry the dataset name is `outbrain-small`.  I have changed the README accordingly.

**Comment by jermainewang** [comment]
@TristonC A new version 0.1 has been uploaded which includes the fix for your reported issue.
